---
title: "Untitled"
author: "zl2528"
date: "April 22, 2017"
output: html_document
---

```{r setup}
setwd('C:/Users/ZISHUO LI/Downloads/project/data/observation')
ps <- read.csv('price_to_sales.ratio.csv',header = FALSE)
n_rows=nrow(ps)

ps_max=data.frame()
for (i in 1:n_rows){
  inter=max(ps[i,])
  ps_max=rbind(ps_max,inter)
}
ps['index']=1:n_rows
ps_sorted=sort(ps[,1],decreasing=TRUE,index.return=TRUE)
loc_ps=ps_sorted$ix[1:900]


mom <- read.csv("momentum39034.csv",header = FALSE)
n_rows=nrow(mom)

mom_max=data.frame()
for (i in 1:n_rows){
  inter=max(mom[i,])
  mom_max=rbind(mom_max,inter)
}
mom['index']=1:n_rows
mom_sorted=sort(mom[,1],decreasing=TRUE,index.return=TRUE)
loc_mom=mom_sorted$ix[1:900]

selected=intersect(loc_mom,loc_ps)
```

```{r}
Earnings<- read.csv("../06-17 Earnings release.csv")
stocks_selected=Earnings[selected,'Ticker']


long_before <- read.csv('../observation_processed/long_before_earning.csv')
short_after <- read.csv('../observation_processed/short_after_earning.csv')
nrow_longb=nrow(long_before)
nrow_shorta=nrow(short_after)

mom_sa=c()
for (i in 1:nrow_shorta){
  inter=max(short_after[i,'MOMENTUM'])
  mom_sa=c(mom_sa,inter)
} 
mom_sa_selected=sort(mom_sa,decreasing=TRUE,index.return=TRUE)
sa_selected=mom_sa_selected$ix[1:1500]
sa_data_selected=short_after[sa_selected,]


mom_lb=c()
for (i in 1:nrow_longb){
  inter=max(long_before[i,'MOMENTUM'])
  mom_lb=c(mom_lb,inter)
} 
mom_lb_selected=sort(mom_lb,decreasing=TRUE,index.return=TRUE)
lb_selected=mom_lb_selected$ix[1:1500]
lb_data_selected=long_before[lb_selected,]


write.csv(lb_data_selected,'long_before20.csv')
write.csv(sa_data_selected,'short_after20.csv')
```
